//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(EmpleadoMetadata))]
    public partial class Empleado
    {
        public int Id { get; set; }
        public Nullable<int> IdRol { get; set; }
        public string Contrasenia { get; set; }
        public string Nombre { get; set; }
        public string Apellidos { get; set; }
        public string Email { get; set; }
        public Nullable<int> Telefono { get; set; }
        public Nullable<bool> Estado { get; set; }
        public string TokenRecuperacion { get; set; }
    
        public virtual Rol Rol { get; set; }
    }
}
