//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RBs_SpareEntities : DbContext
    {
        public RBs_SpareEntities()
            : base("name=RBs_SpareEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BitacoraEmpleados> BitacoraEmpleados { get; set; }
        public virtual DbSet<BitacoraProductos> BitacoraProductos { get; set; }
        public virtual DbSet<Cita> Cita { get; set; }
        public virtual DbSet<CondicionOrden> CondicionOrden { get; set; }
        public virtual DbSet<Detalle_Orden> Detalle_Orden { get; set; }
        public virtual DbSet<Empleado> Empleado { get; set; }
        public virtual DbSet<MarcaMoto> MarcaMoto { get; set; }
        public virtual DbSet<MarcaProducto> MarcaProducto { get; set; }
        public virtual DbSet<ModeloMoto> ModeloMoto { get; set; }
        public virtual DbSet<Orden> Orden { get; set; }
        public virtual DbSet<Producto> Producto { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<TipoProducto> TipoProducto { get; set; }
    }
}
