//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto()
        {
            this.Detalle_Orden = new HashSet<Detalle_Orden>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdTipoProducto { get; set; }
        public Nullable<int> IdMarca { get; set; }
        public string Descripcion { get; set; }
        public byte[] Imagen { get; set; }
        public Nullable<decimal> PrecioUnidad { get; set; }
        public Nullable<decimal> IVA { get; set; }
        public Nullable<bool> Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle_Orden> Detalle_Orden { get; set; }
        public virtual MarcaProducto MarcaProducto { get; set; }
        public virtual TipoProducto TipoProducto { get; set; }
    }
}
